from dotenv import load_dotenv
import os

from langchain.agents import create_agent
from langchain.tools import tool
from langchain_core.messages import SystemMessage, HumanMessage
from typing import List
from pydantic import BaseModel, Field

from langchain_openai import ChatOpenAI
from tavily import TavilyClient

load_dotenv()

class Source(BaseModel):
    """Represents a source of information to be used by the agent."""
    url: str = Field(..., description="The URL of the source.")

class AgentResponse(BaseModel):
    """Represents the Schema of the response from the agent."""
    answer: str = Field(..., description="The answer generated by the agent.")
    sources: List[Source] = Field(default_factory=list, description="The sources used to generate the response.")

tavily = TavilyClient()
@tool
def search(query: str) -> str:
   """Searches on the internet for the given query and returns the result.
    Args:
        query (str): The search query.
    Returns:
        str: The search result.
   """
   print(f"Searching for: {query}")
   return tavily.search(query=query)

def main():
    print("Starting the agent...")
    llm = ChatOpenAI(
        model="gpt-4o",
        temperature=0,
        openai_api_key=os.environ.get("OPENAI_API_KEY"),
    )
    tools = [search]
    agent = create_agent(
        model=llm,
        tools=tools,
        response_format=AgentResponse
    )
    
    response = agent.invoke({"messages": [HumanMessage(content="List 3 AI engineer job openings in Bangalore and list their details from LinkedIn.")], "agent_scratchpad": ""})
    print(response)
    


if __name__ == "__main__":
    main()
